version: '2'

services:
  app1:
    image: netcore_mvc_image
    environment:
      - LOGGING_DIR=/logs/
  app2:
    image: netcore_mvc_image
    environment:
      - LOGGING_DIR=/logs/
  app3:
    image: netcore_mvc_image
    environment:
      - LOGGING_DIR=/logs/

  nginx:
    image: netcore_nginx
    links:
     - app1:app1
     - app2:app2
     - app3:app3
    ports:
     - "1234:1234"